# Sample .travis.yml for R projects

#language: r
language: c
warnings_are_errors: true
sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  ## For installing all CRAN dependencies using rpack's DESCRIPTION
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs


env:
 global:
   #- CRAN: http://cran.rstudio.com
   - CRAN: http://cran.univ-lyon1.fr/

notifications:
  email:
    on_success: change
    on_failure: change
